=== Rustamw888/GoJava/src/main/java/Lesson_48/part_1/books.xsd
<?Lesson_48 version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"> <!-- xsd документ -->

  <xs:element name="books">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="book" type="book" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="book">
    <xs:sequence>
      <xs:element name="title" type="xs:string"/>
      <xs:element name="autor" type="xs:string"/>
      <xs:element name="count_page" type="xs:string"/>
      <xs:element name="year" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string"/> <!-- атрибуты указываем в конце,
     после указания внутренних тэгов, комплексного тэга book-->
  </xs:complexType>

</xs:schema>

=== Rustamw888/GoJava/src/main/java/Lesson_48/part_1/books.xml
<?Lesson_48 version="1.0" encoding="UTF-8"?>

<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="books.xsd"> <!-- На каком сайте эта схема находится
       и сам файл из нашего проекта, -->

  <book id="1">
    <title>The Great American Novel</title>
    <autor>Mark Twain</autor>
    <count_page>500</count_page>
    <year>1998</year>
  </book>

  <book id="2">
    <title>Java SE 8</title>
    <autor>Gilbert Shildt</autor>
    <count_page>1500</count_page>
    <year>2008</year>
  </book>


</books>
